AWSTemplateFormatVersion: 2010-09-09
Description: Deploys a Fargate cluster

Parameters:

  ProjectName:
    Description: Project Name
    Type: String
  ClusterName:
    Description: Fargate Cluster Name
    Type: String

Resources:

  FargateCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref ClusterName

Outputs:

  FargateCluster:
    Description: Fargate Cluster
    Value: !Ref FargateCluster
